remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
minima:
  skin: solarized-dark
  social_links:
    - title: Basic English
      icon: youtube
      url: "https://www.youtube.com/@BasicEnglish40"
google_analytics: G-NV3JM1YPWH
